### ISSUE TITLE
Support some kind of "default" target

### ISSUE THREAD

**Issue by cf-pub-tools** [concourse/fly#101]
For example, if I only have a single target registered with fly and my token for it is still valid, I would expect `fly` commands to just use that target when running subcommands.

I would also be fine with having to specify the default in `.flyrc` or something.

**Comment by vito** [comment]
I think this is a misfeature. `fly` commands are particularly powerful, and it'd be way too easy to run them against the wrong environment. It's intentionally stateless. I agree that if you have one target it feels a little overkill, but I don't like default behavior that suddenly becomes confusing (i.e. because someone saved another target, and there's no way to remove them, and maybe you don't want it removed, etc...).

**Comment by keen99** [comment]
this decision is documented here for reference - https://concourse.ci/fly-login.html

just to throw an opinion out there - I suspect that the large bulk of organizations that might adopt this are going to be single-target orgs.  the larger orgs that would run multiple CI clusters would generally be the exception (and I've worked for a few).   within those orgs, the bulk of individuals would still only operate against one of those clusters.

leaving the option to the users is just good behavior.  the current behavior is user-hostile.  if a user *chooses* to set a default and then adds another target and mis-chooses....well, that's their fault.   they could just as easily up arrow and change the wrong history command - should we remove command history too?     

I totally agree with the decision to default to requiring a target to be specified - but having to add `-t mytarget` to every single command is a painful barrier to entry.    

I'll probably just move and wrap fly with my own wrapper, but I'll have to explain that to my users if we decide to actually roll this out.

**Comment by vito** [comment]
@keen99 Something is not user-hostile just because you don't like it. I personally love never worrying about what my current target is, and I know many others do, too. BOSH had a similar pattern in its CLI's progression. It used to be stateful, leading to lots of mistakes. Prompts about the current target don't help; it just builds muscle memory and still leads to deleted production deployments or, in Fly's case, things like the production pipeline being configured against your local dev VM. The BOSH CLI now follows the same model as `fly`, having you explicitly pass the target environment on every command. This has made me trust it a lot more, and has made it much easier to run against multiple targets.

Having a single target forever is one use case out of many. I know plenty of teams with multiple targets if not just to have per-team targets, and I know plenty of teams that have local VMs for running builds as part of their development workflow, in addition to a single CI running their production pipelines. Running against the wrong target can have disastrous effects, and honestly it's not *that* painful to just run `fly -t <foo>`. Shell history is there for a reason.

It's not a matter of leaving the option to the users. It's our job to not hand our users a loaded gun, just as much as it's our job to provide them with useful tooling.

**Comment by keen99** [comment]
I'm not here to argue this, simply to express a user who would have to train other users opinion.

but:

https://en.wiktionary.org/wiki/user-hostile

```user-hostile (comparative more user-hostile, superlative most user-hostile)
Difficult to use, especially for an untrained user.  [quotations ▼]
```

I think that having to add `--target target` every single execution is exactly in line with the definition of user hostile.   (especially since it took me 20 minutes of google searching to figure out -what- a `target` was supposed to be since when it's referenced it all it's never defined.)

But enough - that was my opinion and I opted to express it.
