### ISSUE TITLE
Fly should have a nicer installer on macOS

### ISSUE THREAD

**Issue by ratkins** [concourse/fly#141]
According to [this](https://github.com/concourse/homebrew-tap/issues/1#issuecomment-128770275) the homebrew tap is deprecated, but the recommended alternative (clicking the download link on the ATC) gets me a read-only file called `fly` in my `~/Downloads` directory which macOS Finder (Sierra 10.12.2) thinks is a text file. This is not ideal.

Either a working homebrew formula or a macOS installer .pkg file (which would install fly into a location in my $PATH, set it executable) would be a nicer first-run experience.

**Comment by chendrix** [comment]
Two complications:

- How are we supposed to know what is in your PATH? How are we supposed to know a reasonable location for you to want to place this executable binary?
- Homebrew is a poor solution since we don't want you to just download the latest. It should be the one tied to your concourse installation.

What you download *is* an executable, it just hasn't had its executable bit set on it (which is why you need to `chmod +x`). 

If you know of any binary-only installers, I'd be interested in looking at them for reference. As far as I know of, I've only seen "Drag this .app to /Applications"

**Comment by ratkins** [comment]
If you want to create a `.pkg`, you can apparently do that with [`pkgbuild`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pkgbuild.1.html) and [this](http://apple.stackexchange.com/questions/215216/el-capitan-where-to-install-application) implies `/usr/local/bin` will always be in the path on modern macOS systems. If it's not, you can add it (maybe in `/etc/profile`?) in a `postinstall` script that is part of your `pkg`.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1065
