### ISSUE TITLE
fly `--paused=false` feature not working, also inconsistent UI behavior

### ISSUE THREAD

**Issue by qanx** [concourse/fly#24]
When I initially deploy a pipeline, it's in the paused state even with the `--paused=false` flag:

```
$ fly -t tutorial configure -c pipeline.yml job-dummy --paused=false
resources:
  resource resource-dummy has been added:
    name: resource-dummy
    type: dummy
    source: {}

jobs:
  job job-dummy has been added:
    name: job-dummy
    public: true
    serial: true
    plan:
    - put: resource-dummy

apply configuration? (y/n): y
pipeline created!
you can view your pipeline here: http://192.168.100.4:8080/pipelines/job-dummy

the pipeline is currently paused. to unpause, either:
  - run again with --paused=false
  - click play next to the pipeline in the web ui
```
When I re-run the command immediately, with the `--paused=false` flag, I see this:

```
$ fly -t tutorial configure -c pipeline.yml job-dummy --paused=false
apply configuration? (y/n): y
configuration updated
```
Which seems to indicate the pipeline is unpaused (since it doesn't give the paused notice); however, it is actually still paused, which I saw when I went to the UI and saw the blue bar at the top:

![Initial Paused State](https://s3.amazonaws.com/f.cl.ly/items/3X302y3h0f2H151S211o/Initial_deploy_pause.png)

Since using the `--paused=false` flag fails to unpause the pipeline from the CLI, I tried to unpause the pipeline in the UI; however, there is an issue unpausing. Click on `job-dummy` to view the job:

![Pause button on the page](https://s3.amazonaws.com/f.cl.ly/items/0l3E1j2L370I2C2U3k0l/Initial_deploy_pause_button.png)

I there is a pause icon next to the name of the job, but if I click it the pipeline is actually *still* paused,  even though the icon changes to a play icon, as evidenced by the blue bar:

![Play button on the page](https://s3.amazonaws.com/f.cl.ly/items/2t0T0j3u1Z3u0Q3b3b39/Initial_deploy_button_click.png)

In fact, the only way to unpause the pipeline is by clicking the other play button, hidden in the menu in the upper left corner:

![Play button in menu](https://s3.amazonaws.com/f.cl.ly/items/290Q0H0y2v3F2U2m0A1C/Initial_deploy_menu_button.png)

Note that the state of the play button in the menu does not match the state of the play/pause button that is next to the pipeline name (`job-dummy`). Only once this blue play button in the left menu has been clicked will the pipeline be unpaused:

![Unpaused pipeline](https://s3.amazonaws.com/f.cl.ly/items/2y3F0s3R2f2O1s0y0w16/Initial_deploy_menu_button_click_unpause.png)

Once the pipeline is unpaused from the menu and is run for the first time, the play/pause button next to the pipeline name permanently disappears:

![First run unpaused](https://s3.amazonaws.com/f.cl.ly/items/2R1B1y2T3J470V2D0Q3E/Pipeline_run_unpaused.png)

Note that it remains gone, even when the pipeline is paused again:

![First run paused](https://s3.amazonaws.com/f.cl.ly/items/00320k1T292K261F0H0t/Pipeline_run_paused.png)

Can the functionality of the play/pause button on the job page please either be repaired or removed to avoid confusion? Also, can the `fly` command be updated so that when a pipeline is deployed with `--paused=false` that the pipeline is not initially paused? Forcing UI interaction makes scripting difficult :-/

What I am running:

* The latest `fly` binary - `0.0.1` (synced)
* The latest `concourse/lite` box - `0.60.1`

**Comment by vito** [comment]
Thanks for the detailed report + screenshots! Those clear things up.

A few things:

* Not sure what's going on there with `--paused=false`; it "works on my machine". It may be our stupid option parser; try moving the flag to before the pipeline name? Are you absolutely sure you've synced from the right target and are running the right binary? If the CLI is too old it may just be ignoring it as an unknown flag.

* The UX around paused jobs vs. paused pipelines could definitely be improved. To explain the last three pictures, what's actually happening is now that the job has a build, it takes you to the *build*, rather than the *job*. So the first of the 3 screenshots with the button is the job, and the next 2 are of the job's first build. As soon as a job has any builds at all, clicking it in the pipeline takes you to the latest one rather than the job page (to prevent an extra click).

* A few things can be paused in Concourse: jobs and resources, and entire pipelines (which has the effect of pausing all jobs/resources contained in it). So there are a few paused buttons sprinkled throughout the UI for the individual elements.

* Pipelines default to paused as a safety net. It's pretty terrifying to have a really important pipeline immediately spring into life immediately after configuring it, before you can be sure it's correct. If the CLI option parsing worked this wouldn't be an issue.

**Comment by qanx** [comment]
Thank you for getting back to me!

> Not sure what's going on there with `--paused=false`; it "works on my machine". It may be our stupid option parser; try moving the flag to before the pipeline name? 

akdjfadh. That worked. This is the second time something like this has happened to me, heh. The first time was when it wasn't recognizing my `credentials.yml` and throwing unbound variable errors. I probably should have tried moving the `--paused=false` around. Sorry about that :-/ 

As a feature request, is it possible to change parsers so the flag order doesn't matter? Because that would be nice :)

> If the CLI is too old it may just be ignoring it as an unknown flag.

Funny story, the first time I encountered `--paused=false` I couldn't run it because it was an unrecognized option. This actually threw an error rather than ignoring it silently. I was using version `0.0.1` and thought I was using the latest - until someone suggested I run `fly sync`. After that `--paused=false` didn't cause any errors, and appeared in the `fly` help, although I was pretty confused since my `fly` version was still `0.0.1`. I was told there are two releases with that version number? :)

> The UX around paused jobs vs. paused pipelines could definitely be improved. ...

Ah, thank you for explaining what was going on there :)

> Pipelines default to paused as a safety net. It's pretty terrifying to have a really important pipeline immediately spring into life immediately after configuring it, before you can be sure it's correct. 

I thought that the default behavior before the paused feature was to have it not paused but not triggered either. So even though it wasn't paused, it wasn't actively running jobs/etc. either. Were you guys trying to achieve something beyond that?

**Comment by vito** [comment]
Glad it was just the option parsing; we'll probably be switching libraries entirely and just rewrite `fly` using a different CLI framework with more reasonable parsing.

If a pipeline's not paused it's effectively active, even if things don't trigger immediately. It'll start checking for versions, potentially find some, and run any jobs that have `trigger: true` set on their inputs. So yeah, it's dangerous to just have one start running immediately after configuring since you may want to bring it up and eyeball it.

**Comment by qanx** [comment]
Fair enough - thank you for the explanation! Now that I know your parsing is sensitive to order I'll be more mindful when I try writing shell scripts around it :) 

Thanks again! :+1: :

**Comment by vito** [comment]
Assuming I can close this now; we've got a track of work coming up that'll fix the `fly` argument/flag order issue.

I'll think about the pausing web UI; we don't have a designer at the moment and may be getting one at some point so I'm hesitant to sink too much time into it right now (relative to other things to fix). For now it may be better to just start on some web UI docs or something.
