### ISSUE TITLE
fly hijack --check doesn't work?

### ISSUE THREAD

**Issue by benmoss** [concourse/fly#44]
```
$ fly -t diego hijack --check main/diego-release
proc_starter: ExecAsUser: system: program 'bash' was not found in $PATH: exec: "bash": executable file not found in $PATH
```

not sure if i am doing something wrong here, but from my understanding of this feature i should be able to ssh into resource containers.

**Comment by benmoss** [comment]
So discovered I could just append `/bin/sh` and it works, but this still feels slightly buggy.

**Comment by xoebus** [comment]
Yeah, the resource images are really stripped down to the point where they don't even have `bash`. As you've found you need to append `sh` to the end of the command for it to start that shell.

We don't want to make it the default because it's unfortunately common to make `/bin/sh` be an unexpected shell like `dash`. Optimizing for an infrequent action (hijacking into a check container) compared to hijacking into a build also weighs against switching the default to `/bin/sh`.

We might be able to try `/bin/bash` and if that fails then try `/bin/sh`. Or just always use `/bin/sh` for check containers. I'll have a think.

/cc @vito

**Comment by maryamklabib** [comment]
![screen shot 2016-05-31 at 2 58 33 pm](https://cloud.githubusercontent.com/assets/4147717/15691947/83d44f72-2740-11e6-90a2-667dd1da3268.png)

Just ran into this. Would be helpful if this is still open for consideration.

**Comment by benmoss** [comment]
Closing as a dup of #73 which is getting worked on :)
