### ISSUE TITLE
fly execute -x ignores .git directory

### ISSUE THREAD

**Issue by cwlbraa** [concourse/fly#55]
This presents problems when external dependencies rely on git to compile (_coughetcdcough_).

It'd be great if we could ignore .gitignored files without ignoring .git configuration.

**Comment by cwlbraa** [comment]
code in question is here:

https://github.com/concourse/fly/blob/master/commands/internal/executehelpers/uploads.go#L67

I'd love to fix this via PR if I can get a sticker for it.

**Comment by vito** [comment]
This is intentional; the `.git` directory can be very large and the common use case for `-x` is to run tasks against the code as-is, ignoring the `git` aspects of it. I could see there being another flag to include `.git` but it may be worth thinking of a different interface (e.g. a `.flyignore`) instead of adding flags upon flags.

**Comment by cwlbraa** [comment]
but I want concourse to solve all the problems I have with etcd! /s

At the very least '-x' needs a documentation change, then. I want a sticker.

As another alternative, would an -exclude-git (-g) flag be appropriate?

**Comment by tomwhoiscontrary** [comment]
In my case, we have a step in a pipeline which creates BOSH final releases, and as part of this, it commits the BOSH-created metadata. That needs the .git directory around. However, it doesn't need dev releases, blobs, and so on. Being able to include the .git directory but not all the ignored stuff outside it would be really useful for testing.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1087
