### ISSUE TITLE
version fly the same as concourse bosh-release

### ISSUE THREAD

**Issue by robdimsdale** [concourse/fly#9]
it would be nice for the version of fly to be consistent with the version of the the bosh-release. It would also help in debugging any issues, as there is a meaningful version to which submitter can refer.

I don't know how e.g. the CF CLI manages this, but it shouldn't be too hard?

**Comment by vito** [comment]
There's a story in this in the backlog already FYI. Also one for being able
to see it from the web ui. Shouldn't be too tricky since they're all from
the same release. I'd like to tackle this at the same time as creating
release candidate tarballs and passing them through the pipeline, and then
using the new finalize-release bosh command to promote it.

**Comment by robdimsdale** [comment]
Ok I see that at tracker story at [80652632](https://www.pivotaltracker.com/story/show/80652632).

The other thoughts make sense. I'll close this issue now, as it's already captured in tracker.

**Comment by robdimsdale** [comment]
@vito @xoebus we've seen at least one comment from the community about how this would be useful. I'd also like to +1 this, as we're running into weird behaviors with incompatibilities between fly and atc, and we have no idea which version of fly we're using.

Because of the above, and the fact we're moving to github issues to open up the conversation, I'm going to reopen this issue.

**Comment by robdimsdale** [comment]
another +1 (or +2) - we have spent nearly an hour trying to figure out why `fly configure` isn't accepting `--vars-from` which indicates that it is an old version but we can't prove which version of fly we're using, because they all have the same version
